# Generated by Django 3.2.9 on 2022-11-14 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_alter_exam_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='true_answered_users',
        ),
    ]
