# Generated by Django 3.2.9 on 2022-11-15 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_remove_question_true_answered_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'verbose_name': 'Test', 'verbose_name_plural': 'Testlar'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Savol', 'verbose_name_plural': 'Savollar'},
        ),
        migrations.AlterModelOptions(
            name='userexam',
            options={'verbose_name': 'Foydalanuvchi Testi', 'verbose_name_plural': 'Foydalanuvchi Testlari'},
        ),
    ]
