# Generated by Django 3.2.9 on 2022-11-30 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_auto_20221129_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='questions',
            field=models.ManyToManyField(db_index=True, related_name='examm', to='exam.Question'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='stage',
            field=models.CharField(db_index=True, default=0, max_length=16),
        ),
        migrations.AlterField(
            model_name='exam',
            name='title',
            field=models.CharField(db_index=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='userexam',
            name='is_finished',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='userexamanswer',
            name='answered',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='userexamanswer',
            name='is_correct',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
