# Generated by Django 3.2.9 on 2022-12-01 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_auto_20221130_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='questions',
            field=models.ManyToManyField(db_index=True, related_name='question_exams', to='exam.Question'),
        ),
        migrations.AlterField(
            model_name='userexam',
            name='questions',
            field=models.ManyToManyField(related_name='question_user_exams', to='exam.Question'),
        ),
        migrations.AlterField(
            model_name='userexamanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_user_exam_answer', to='exam.question'),
        ),
        migrations.AlterField(
            model_name='userexamanswer',
            name='user_exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_exam_answer', to='exam.userexam'),
        ),
    ]
