# Generated by Django 3.2.9 on 2022-11-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20221020_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_busy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_random_opponent_waites',
            field=models.BooleanField(default=False),
        ),
    ]
