# Generated by Django 3.2.9 on 2022-11-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20221102_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='challenge_id',
            field=models.CharField(default='no', max_length=256),
        ),
    ]
