# Generated by Django 3.2.9 on 2022-11-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_challenge_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='challenges_count',
            field=models.IntegerField(default=0),
        ),
    ]
