# Generated by Django 3.2.9 on 2022-11-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_challenges_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_ended_challenge_waites',
            field=models.BooleanField(default=False),
        ),
    ]
