# Generated by Django 3.2.9 on 2022-10-20 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exam', '0001_initial'),
        ('users', '0004_auto_20221020_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(blank=True, max_length=16, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('questions', models.ManyToManyField(to='exam.Question')),
            ],
            options={
                'verbose_name': 'Challenge',
                'verbose_name_plural': 'Challengelar',
            },
        ),
        migrations.CreateModel(
            name='UserChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_random_opponent', models.BooleanField(default=False)),
                ('user_score', models.IntegerField(default=0)),
                ('opponent_score', models.IntegerField(default=0)),
                ('user_started_at', models.DateTimeField(null=True)),
                ('user_finished_at', models.DateTimeField(null=True)),
                ('opponent_started_at', models.DateTimeField(null=True)),
                ('opponent_finished_at', models.DateTimeField(null=True)),
                ('is_user_finished', models.BooleanField(default=False)),
                ('is_opponent_finished', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_challenge_message_id', models.CharField(max_length=1024, null=True)),
                ('created_challenge_chat_id', models.CharField(max_length=1024, null=True)),
                ('user_message_id', models.CharField(max_length=1024, null=True)),
                ('opponent_message_id', models.CharField(max_length=1024, null=True)),
                ('user_chat_id', models.CharField(max_length=1024, null=True)),
                ('opponent_chat_id', models.CharField(max_length=1024, null=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_challenge.challenge')),
                ('opponent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='as_opponent', to='users.user')),
                ('questions', models.ManyToManyField(to='exam.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_owner', to='users.user')),
                ('users', models.ManyToManyField(related_name='user_challenges', to='users.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserChallengeAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_ids', models.CharField(max_length=255, null=True)),
                ('answered', models.BooleanField(default=False)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
                ('user_challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='group_challenge.userchallenge')),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars_count', models.IntegerField(default=0)),
                ('old_stars_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
                ('user_challenge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='group_challenge.userchallenge')),
            ],
        ),
    ]
