# Generated by Django 3.2.9 on 2022-11-05 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_challenge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchallenge',
            name='in_proccecc',
            field=models.BooleanField(default=False),
        ),
    ]
