# Generated by Django 3.2.9 on 2022-11-15 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_is_ended_challenge_waites'),
        ('group_challenge', '0003_userchallenge_is_waited_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchallenge',
            name='opponent_timer',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='userchallenge',
            name='user_timer',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='userchallenge',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner_user_challenges', to='users.user'),
        ),
    ]
