# Generated by Django 3.2.9 on 2022-11-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_challenge', '0004_auto_20221115_0852'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='challenge',
            options={'verbose_name': 'Bellashuv', 'verbose_name_plural': 'Bellashuvlar'},
        ),
        migrations.AlterModelOptions(
            name='userchallenge',
            options={'verbose_name': 'Foydalanuvchi Bellashuvi', 'verbose_name_plural': 'Foydalanuvchi Bellashuvlari'},
        ),
        migrations.AddField(
            model_name='userchallengeanswer',
            name='number',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
