# Generated by Django 3.2.9 on 2022-11-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_challenge', '0005_auto_20221115_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userchallengeanswer',
            name='option_ids',
        ),
        migrations.AddField(
            model_name='userchallengeanswer',
            name='option_id',
            field=models.IntegerField(default=0),
        ),
    ]
