# Generated by Django 3.2.9 on 2022-11-29 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_options'),
        ('group_challenge', '0006_auto_20221115_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='users.user'),
        ),
        migrations.AlterField(
            model_name='userchallengeanswer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_answers', to='users.user'),
        ),
    ]
