# Generated by Django 3.2.9 on 2022-11-29 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_auto_20221129_1704'),
        ('group_challenge', '0007_auto_20221129_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='questions',
            field=models.ManyToManyField(related_name='challenge_questions', to='exam.Question'),
        ),
        migrations.AlterField(
            model_name='userchallenge',
            name='questions',
            field=models.ManyToManyField(related_name='user_challenge_questions', to='exam.Question'),
        ),
        migrations.AlterField(
            model_name='userchallengeanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_challenge_answer_question', to='exam.question'),
        ),
    ]
