# Generated by Django 3.2.9 on 2022-11-30 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_options'),
        ('group_challenge', '0008_auto_20221129_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchallenge',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='userchallenge',
            name='is_random_opponent',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='userchallenge',
            name='is_waited_challenge',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='userchallenge',
            name='users',
            field=models.ManyToManyField(db_index=True, related_name='user_challenges', to='users.User'),
        ),
        migrations.AlterField(
            model_name='userchallengeanswer',
            name='answered',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='userchallengeanswer',
            name='is_correct',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
