# Generated by Django 3.2.9 on 2022-12-01 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_auto_20221201_1017'),
        ('users', '0009_alter_user_options'),
        ('group_challenge', '0009_auto_20221130_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='questions',
            field=models.ManyToManyField(related_name='question_challenges', to='exam.Question'),
        ),
        migrations.AlterField(
            model_name='userchallenge',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_user_challenge', to='group_challenge.challenge'),
        ),
        migrations.AlterField(
            model_name='userchallenge',
            name='opponent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opponent_user_challenge', to='users.user'),
        ),
        migrations.AlterField(
            model_name='userchallenge',
            name='questions',
            field=models.ManyToManyField(related_name='question_user_challenges', to='exam.Question'),
        ),
        migrations.AlterField(
            model_name='userchallenge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_user_challenge', to='users.user'),
        ),
        migrations.AlterField(
            model_name='userchallenge',
            name='users',
            field=models.ManyToManyField(db_index=True, related_name='user_user_challenges', to='users.User'),
        ),
        migrations.AlterField(
            model_name='userchallenge',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner_user_challenge', to='users.user'),
        ),
        migrations.AlterField(
            model_name='userchallengeanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_user_challenge_answers', to='exam.question'),
        ),
        migrations.AlterField(
            model_name='userchallengeanswer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_challenge_answers', to='users.user'),
        ),
        migrations.AlterField(
            model_name='userchallengeanswer',
            name='user_challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='group_challenge.userchallenge'),
        ),
    ]
